dotfiles_dir = ".dotfiles"

[settings]
vars = [ "themes/gruvbox.toml" ]

hooks = [ "dwmc quit 1" ]

[settings.dots]

vimrc = { source = "vim/.vimrc", target = ".vimrc" }
nvim = { source = "vim/nvim", target = ".config/nvim" }
vim_autoload = { source = "vim/autoload", target = ".vim/autoload" }
vim_colors = { source = "vim/colors", target = ".vim/colors" }

zshrc = { source = "zsh/.zshrc", target = ".zshrc" }

fonts_conf = { source = "fonts/fonts.conf", target = ".fonts.conf" }
fonts = { source = "fonts/Fonts", target = ".Fonts" }

doom_emacs = { source = "doom.d", target = ".doom.d" }
bin = { source = "bin", target = ".bin" }

picom = { source = "picom/picom.conf", target = ".config/picom.conf" }

rofi_slate  = { source = "rofi/themes/slate-gruvbox.rasi", target = ".local/share/rofi/themes/slate-gruvbox.rasi" }

polybar = { source = "polybar", target = ".config/polybar" }

alacritty = { source = "alacritty", target = ".config/alacritty" }

bspwm = { source = "bspwm", target = ".config/bspwm" }
sxhkd = { source = "sxhkd", target = ".config/sxhkd" }
dunst = { source = "dunst/dunstrc", target = ".config/dunst/dunstrc" }

fish_config = { source = "fish/config.fish", target = ".config/fish/config.fish" }
fish_confd = { source = "fish/conf.d", target = ".config/fish/conf.d" }
fish_functions = { source = "fish/functions", target = ".config/fish/functions" }
fish_omf = { source = "fish/omf", target = ".config/omf" }

mimi = { source = "mimi", target = ".config/mimi" }
transmission-daemon = { source = "transmission-daemon", target = ".config/transmission-daemon" }
spicetify = { source = "spicetify", target = ".config/spicetify" }

gitconfig = { source = "git/gitconfig", target = ".gitconfig" }
xresources = { source = "x/Xresources", target = ".Xresources" }
xprofile = { source = "x/xprofile", target = ".xprofile" }
offlineimap = { source = "offlineimap/offlineimaprc", target = ".offlineimaprc" }

dwm = { source = "dwm", target = ".config/dwm" }
vscode = { source = "vscode/settings.json", target = ".config/Code - OSS/User/settings.json" }
# = { source = "", target = "" }
