dotfiles_dir = ".dotfiles"
gpg_user_id = "kajetan.puchalski@tuta.io"

[settings]
vars = [ "themes/gruvbox.toml" ]

hooks = [ "dwmc quit 1" ]

[settings.dots]

fonts_conf = { source = "fontconfig/fonts.conf", target = ".config/fontconfig/fonts.conf" }
fonts = { source = "fontconfig/Fonts", target = ".Fonts" }

spacevim = { source = "spacevim", target = ".config/spacevim" }
doom_emacs = { source = "doom", target = ".config/doom" }
bin = { source = "bin", target = ".bin" }

picom = { source = "picom/picom.conf", target = ".config/picom.conf" }

rofi_slate  = { source = "rofi/themes/slate-gruvbox.rasi", target = ".local/share/rofi/themes/slate-gruvbox.rasi" }

polybar = { source = "polybar", target = ".config/polybar" }

alacritty = { source = "alacritty", target = ".config/alacritty" }

bspwm = { source = "bspwm", target = ".config/bspwm" }
sxhkd = { source = "sxhkd", target = ".config/sxhkd" }
dunst = { source = "dunst/dunstrc", target = ".config/dunst/dunstrc" }

fish_config = { source = "fish/config.fish", target = ".config/fish/config.fish" }
fish_confd = { source = "fish/conf.d", target = ".config/fish/conf.d" }
fish_functions = { source = "fish/functions", target = ".config/fish/functions" }
fish_omf = { source = "fish/omf", target = ".config/omf" }
zshrc = { source = "zsh/zshrc", target = ".config/zsh/.zshrc" }

mimi = { source = "mimi", target = ".config/mimi" }
spicetify = { source = "spicetify", target = ".config/spicetify" }
transmission-daemon = { source = "transmission-daemon", target = ".config/transmission-daemon" }

gitconfig = { source = "git/gitconfig", target = ".gitconfig" }
tig = { source = "tig/config", target = ".config/tig/config" }

xresources = { source = "X11/Xresources", target = ".Xresources" }
xprofile = { source = "X11/xprofile", target = ".xprofile" }
offlineimap = { source = "offlineimap/offlineimaprc", target = ".offlineimaprc" }

dwm = { source = "dwm", target = ".config/dwm" }
vscode = { source = "vscode/settings.json", target = ".config/Code - OSS/User/settings.json" }

# = { source = "", target = "" }
