theme = "gruvbox"

[editor]
line-number = "relative"
text-width = 100

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "block"

[editor.file-picker]
hidden = true

[keys.normal]
"#" = "goto_line_end"
"$" = "goto_line_start"
"G" = "goto_last_line"
"w" = 'move_next_sub_word_start'
"b" = 'move_prev_sub_word_start'
"e" = 'move_next_sub_word_end'
"W" = 'move_next_word_start'
"B" = 'move_prev_word_start'
"E" = 'move_next_word_end'
"%" = "match_brackets"
"A-s" = "select_next_sibling"
"A-S" = "select_prev_sibling"

[keys.select]
"#" = "goto_line_end"
"$" = "goto_line_start"
"G" = "goto_last_line"
"w" = 'extend_next_sub_word_start'
"b" = 'extend_prev_sub_word_start'
"e" = 'extend_next_sub_word_end'
"W" = 'extend_next_word_start'
"B" = 'extend_prev_word_start'
"E" = 'extend_next_word_end'

[keys.normal.space]
"q" = ":quit"
"Q" = ":quit-all!"

[keys.normal.space.i]
"r" = ":config-reload"

[keys.normal.space.f]
"f" = "file_picker"
"s" = ":write"

[keys.normal.space.b]
"b" = "buffer_picker"
"n" = "goto_next_buffer"
"p" = "goto_previous_buffer"
"r" = ":reload"
"d" = ":buffer-close"

