# ----------
# Plugins
# ----------

source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "danr/kakoune-easymotion"
plug "occivink/kakoune-vertical-selection"
plug "andreyorst/fzf.kak"
plug "alexherbo2/auto-pairs.kak"
plug 'delapouite/kakoune-buffers'
plug 'occivink/kakoune-find'
plug 'h-youhei/kakoune-surround'
plug 'occivink/kakoune-sudo-write'
plug 'nesyamun/nord-kakoune'
plug 'jjk96/kakoune-rainbow'
plug 'delapouite/kakoune-auto-percent'

plug "jdugan6240/powerline.kak" config %{
    powerline-start
}

plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}

plug 'delapouite/kakoune-text-objects' %{
    text-object-map
}

plug 'ftonneau/wordcount.kak'

plug 'delapouite/kakoune-mirror' %{
    # Suggested mapping
    map global normal "'" ': enter-user-mode -lock mirror<ret>'
}

plug 'delapouite/kakoune-user-modes' %{
  # Suggested mappings
  map global user a ': enter-user-mode anchor<ret>'   -docstring 'Anchor mode'
  map global user e ': enter-user-mode echo<ret>'     -docstring 'Echo mode'
  map global user f ': enter-user-mode format<ret>'   -docstring 'Format mode'
  map global user i ': enter-user-mode enter<ret>'    -docstring 'Enter mode'
  map global user k ': enter-user-mode keep<ret>'     -docstring 'Keep mode'
  map global user l ': enter-user-mode lint<ret>'     -docstring 'Lint mode'
  map global user r ': enter-user-mode rotation<ret>' -docstring 'Rotation mode'
  map global user t ': enter-user-mode trim<ret>'     -docstring 'Trim mode'
  map global user / ': enter-user-mode search<ret>'   -docstring 'Search mode'
}

# -------------------
# General settings
# -------------------

colorscheme gruvbox

# ---------------
# Key mappings
# ---------------

map global user g -docstring "EasyMotion" ': enter-user-mode easymotion<ret>'
map global user b ':enter-buffers-mode<ret>'              -docstring 'Buffers'
map global user B ':enter-user-mode -lock buffers<ret>'   -docstring 'Buffers (lock)'

declare-user-mode vertical-select
map global vertical-select v     ': vertical-selection-down<ret>' -docstring 'Select down'
map global vertical-select <a-v> ': vertical-selection-up<ret>' -docstring 'Select up'
map global vertical-select V     ': vertical-selection-up-and-down<ret>' -docstring 'Select up & down'
map global user v ':enter-user-mode vertical-select<ret>' -docstring 'Vertical select'

declare-user-mode surround
map global surround s ':surround<ret>' -docstring 'Surround'
map global surround c ':change-surround<ret>' -docstring 'Change'
map global surround d ':delete-surround<ret>' -docstring 'Delete'
map global surround t ':select-surrounding-tag<ret>' -docstring 'Select tag'
map global user s ':enter-user-mode surround<ret>' -docstring 'Surround'

map global user w ':write<ret>' -docstring 'Write'
map global user q ':quit<ret>' -docstring 'Quit'
map global user Q ':quit!<ret>' -docstring 'Force quit'

map global normal <space> ,
map global normal , <space>

alias global u enter-user-mode

# --------
# Hooks
# --------

hook global InsertChar \. %{ try %{
    exec -draft hH <a-k>,\.<ret> d
    exec <esc>
}}

hook global WinDisplay .* info-buffers

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
}

hook global InsertChar \t %{ exec -draft -itersel h@ }                      
set global tabstop 4                                                        
set global indentwidth 4

# ---------------
# Highlighters
# ---------------

add-highlighter global/ number-lines -separator '  '
set-face global LineNumbers rgb:696969,default
set-face global EasyMotionForeground rgb:000000,default
set-option global ui_options ncurses_assistant=none
set-option global rainbow_faces "rgb:ff0000" "rgb:00ff00" "rgb:0000ff"
