#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "config#before"
    bootstrap_after = "config#after"
    lint_on_the_fly = true
    enable_ale = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "ui"
enable_sidebar = true

[[layers]]
name = "sudo"

[[layers]]
name = "fzf"

[[layers]]
name = "cscope"

[[layers]]
name = "lsp"
filetypes = [
  "rust"
]

[[layers]]
name = "lang#c"
clang_executable = "/usr/bin/clang"
clang_flag = ['']
[layer.clang_std]
c = "c11"

[[layers]]
name = "lang#rust"
recommended_style = true
format_on_save = true

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#python"
format_on_save = 1
